services:

  frontend:
    container_name: mostafa-frontend
    build: ./frontend
    image: mostafa-frontend
    environment:
      - REACT_APP_BASE_URL=http://localhost:8000/api/
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000
    depends_on:
      - backend


  backend:
    container_name: mostafa-backend
    build: ./backend
    image: mostafa-backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      dbConnection:
        condition: service_completed_successfully

  dbConnection:
    container_name: mostafa-database-dbConnection
    image: mysql
    command: mysql -hdb -uroot -pmostafa-db-password -e "CREATE DATABASE IF NOT EXISTS mostafa"
    depends_on:
      - db
    restart: on-failure

  db:
    container_name: mostafa-database
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mostafa-db-password
    volumes:
      - mostafa-db-volume:/var/lib/mysql

networks:
  default:
    name: mostafa-network

volumes:
  mostafa-db-volume:
    name: mostafa-db-volume